# Generated by Django 3.1 on 2022-04-30 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mundimoto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=10)),
                ('credit_card', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('fuel', models.IntegerField()),
                ('price', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundimoto.brands')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intial_longitude', models.FloatField()),
                ('initial_latitude', models.FloatField()),
                ('final_longitude', models.FloatField()),
                ('final_latitude', models.FloatField()),
                ('price', models.IntegerField()),
                ('final_at', models.DateTimeField()),
                ('total_km', models.FloatField()),
                ('fuel_level', models.FloatField()),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundimoto.versions')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundimoto.clients')),
            ],
        ),
    ]
