# Generated by Django 3.1 on 2022-04-30 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mundimoto', '0002_brands_clients_logs_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangeBike',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat', models.CharField(max_length=255)),
                ('low', models.IntegerField()),
                ('high', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeCustomerId', models.CharField(max_length=255)),
                ('stripeSubscriptionId', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
