# Generated by Django 3.1 on 2022-05-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundimoto', '0003_rangebike_stripecustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findmotorbike',
            name='Fuel',
        ),
        migrations.AddField(
            model_name='clients',
            name='subscribed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='findmotorbike',
            name='lat1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='findmotorbike',
            name='lat2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='findmotorbike',
            name='lon1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='findmotorbike',
            name='lon2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
