# Generated by Django 4.0.4 on 2022-05-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundimoto', '0004_auto_20220501_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='versions',
            name='possibleKm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='findmotorbike',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
